version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dropout_prediction_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: dropout_prediction
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - dropout_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dropout_prediction_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/dropout_prediction?authSource=admin
      - MONGODB_DB_NAME=dropout_prediction
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
    depends_on:
      - mongodb
    volumes:
      - ./ml/models:/app/ml/models
    networks:
      - dropout_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dropout_prediction_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - dropout_network

volumes:
  mongodb_data:

networks:
  dropout_network:
    driver: bridge
